name: Build and Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Manually fix vulnerabilities
      run: |
        npm install serialize-javascript@^4.0.0
        npm install shell-quote@^1.8.0
        npm install sockjs@^0.3.20
        npm install terser@^4.8.1
        npm install webpack-dev-middleware@^5.3.4
        npm install yargs-parser@^13.1.2

    - name: Run audit and apply fixes
      run: |
        npm audit fix
        npm audit fix --force  # Apply breaking changes fixes if necessary

    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm run test --if-present

    - name: Deploy to Azure Web App
      run: |
        # Add your deployment steps here
        echo "Deploying React App to Azure Web App"
        # Example: az webapp deployment source config --name <app_name> --resource-group <resource_group> --src-path ./build
