name: Build and Deploy React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Updated to Node.js 16

    - name: Install dependencies
      run: |
        npm install
        # Install dependencies and update browserslist db
        npx update-browserslist-db@latest

    - name: Manually fix vulnerabilities
      run: |
        npm install serialize-javascript@^4.0.0
        npm install shell-quote@^1.8.0
        npm install sockjs@^0.3.20
        npm install terser@^4.8.1
        npm install webpack-dev-middleware@^5.3.4
        npm install yargs-parser@^13.1.2

    - name: Run audit and apply fixes
      run: |
        npm audit fix
        npm audit fix --force  # Apply breaking changes fixes if necessary

    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm run test --if-present

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7FA565814271486193F01FAB906028B8 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_57B9E131A8D64671B5A8A020F32DEE2F }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CBF0DDD18E0A47DC83EFDE5B4EA9F28E }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'projectwebapp'  # Replace with your Azure Web App name
        slot-name: 'Production'    # You can adjust this for different slots if needed
        package: './build'  # Deploy the build folder to Azure
